"use client";

import { ArrowLeft } from "lucide-react";
import { useRouter } from "next/navigation";

const PrivacyPolicy = () => {
  const router = useRouter();

  return (
    <div className="m-4 mx-auto max-w-7xl text-foreground">
      <div className="shadow-sm m-6 p-6 border border-border rounded-xl">
        {/* Navigation */}
        <div className="mb-6">
          <button
            onClick={() => router.back()}
            className="group flex items-center gap-2 font-bold text-[10px] text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 uppercase tracking-[0.2em] transition-all"
          >
            <ArrowLeft className="w-4 h-4 transition-transform group-hover:-translate-x-1" />
            Back
          </button>
        </div>

        {/* Header */}
        <header className="mb-10 pb-6 border-zinc-100 dark:border-zinc-900 border-b">
          <h1 className="font-black text-zinc-900 dark:text-zinc-100 text-4xl tracking-tight">
            Privacy Policy
          </h1>
        </header>

        {/* Content */}
        <main className="space-y-10 leading-relaxed">
          <section>
            <h2 className="mb-4 font-bold text-zinc-900 dark:text-zinc-100 text-xl uppercase tracking-tight">
              1. Information Processing
            </h2>
            <p className="opacity-80 mb-4 text-base">
              To provide AI-powered resume analysis, we process the professional data you provide.
              This includes:
            </p>
            <ul className="space-y-3 opacity-80 pl-6 text-base list-disc">
              <li>
                <strong>Resume Content:</strong> Contact details, work history, and skills found in
                your uploaded files.
              </li>
              <li>
                <strong>Analysis Metadata:</strong> Insights generated by our Gemini and Llama
                models based on your profile.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-4 font-bold text-zinc-900 dark:text-zinc-100 text-xl uppercase tracking-tight">
              2. No AI Training Policy
            </h2>
            <p className="opacity-80 text-base">
              We strictly follow a "No Training" policy. Your uploaded resumes and professional data
              are <strong>never used to train</strong> public AI models. Data is processed in a
              transient state solely to generate your ATS score and suggestions.
            </p>
          </section>

          <section className="bg-zinc-50 dark:bg-zinc-900/50 p-6 border-zinc-900 dark:border-zinc-100 border-l-4 rounded-r-xl">
            <p className="font-bold text-zinc-800 dark:text-zinc-200 text-base sm:text-lg italic">
              Transparency: We prioritize your data sovereignty. We do not sell, rent, or trade your
              professional information with third-party recruiters or advertisers.
            </p>
          </section>

          <section>
            <h2 className="mb-4 font-bold text-zinc-900 dark:text-zinc-100 text-xl uppercase tracking-tight">
              3. Data Security
            </h2>
            <p className="opacity-80 text-base">
              Your documents are encrypted using AES-256 standards during transit and at rest.
              Access to your data is restricted to the analysis engine and is automatically purged
              or archived based on your account settings.
            </p>
          </section>

          <section>
            <h2 className="mb-4 font-bold text-zinc-900 dark:text-zinc-100 text-xl uppercase tracking-tight">
              4. Your Control
            </h2>
            <p className="opacity-80 text-base">
              You retain 100% ownership of your data. At any time, you can delete your uploaded
              resumes or permanently wipe your account history from our servers through the user
              dashboard.
            </p>
          </section>
        </main>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
