"use client";

import { useRouter } from "next/navigation";

import { ArrowLeft } from "lucide-react";

const PrivacyPolicy = () => {
  const router = useRouter();

  return (
    <div className="text-foreground m-4 mx-auto max-w-7xl">
      <div className="border-border m-6 rounded-xl border p-6 shadow-sm">
        {/* Navigation */}
        <div className="mb-6">
          <button
            onClick={() => router.back()}
            className="group flex items-center gap-2 text-[10px] font-bold tracking-[0.2em] text-zinc-400 uppercase transition-all hover:text-zinc-900 dark:hover:text-zinc-100"
          >
            <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" />
            Back
          </button>
        </div>

        {/* Header */}
        <header className="mb-10 border-b border-zinc-100 pb-6 dark:border-zinc-900">
          <h1 className="text-4xl font-black tracking-tight text-zinc-900 dark:text-zinc-100">
            Privacy Policy
          </h1>
        </header>

        {/* Content */}
        <main className="space-y-10 leading-relaxed">
          <section>
            <h2 className="mb-4 text-xl font-bold tracking-tight text-zinc-900 uppercase dark:text-zinc-100">
              1. Information Processing
            </h2>
            <p className="mb-4 text-base opacity-80">
              To provide AI-powered resume analysis, we process the professional
              data you provide. This includes:
            </p>
            <ul className="list-disc space-y-3 pl-6 text-base opacity-80">
              <li>
                <strong>Resume Content:</strong> Contact details, work history,
                and skills found in your uploaded files.
              </li>
              <li>
                <strong>Analysis Metadata:</strong> Insights generated by our
                Gemini and Llama models based on your profile.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-bold tracking-tight text-zinc-900 uppercase dark:text-zinc-100">
              2. No AI Training Policy
            </h2>
            <p className="text-base opacity-80">
              We strictly follow a "No Training" policy. Your uploaded resumes
              and professional data are <strong>never used to train</strong>{" "}
              public AI models. Data is processed in a transient state solely to
              generate your ATS score and suggestions.
            </p>
          </section>

          <section className="rounded-r-xl border-l-4 border-zinc-900 bg-zinc-50 p-6 dark:border-zinc-100 dark:bg-zinc-900/50">
            <p className="text-base font-bold text-zinc-800 italic sm:text-lg dark:text-zinc-200">
              Transparency: We prioritize your data sovereignty. We do not sell,
              rent, or trade your professional information with third-party
              recruiters or advertisers.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-bold tracking-tight text-zinc-900 uppercase dark:text-zinc-100">
              3. Data Security
            </h2>
            <p className="text-base opacity-80">
              Your documents are encrypted using AES-256 standards during
              transit and at rest. Access to your data is restricted to the
              analysis engine and is automatically purged or archived based on
              your account settings.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-bold tracking-tight text-zinc-900 uppercase dark:text-zinc-100">
              4. Your Control
            </h2>
            <p className="text-base opacity-80">
              You retain 100% ownership of your data. At any time, you can
              delete your uploaded resumes or permanently wipe your account
              history from our servers through the user dashboard.
            </p>
          </section>
        </main>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
